### ISSUE TITLE
Ambient noises in the VAB

### ISSUE THREAD

**Issue by RowRows** [ensou04/RocketSoundEnhancementDefault#3]
There are ambient construction (drilling etc) in the VAB. How can I turn these off ? even without the RSE config folder I hear them and there is nothing in the default folder to delete.

**Comment by Gordon-Dry** [comment]
You can't - those sounds always have been hardcoded into KSP.

**Comment by ActrixEV** [comment]
Had to jump around forum threads to find this exact issue. The threads I uncovered all pointed universally to this mod as the source of the issue, so I will press on assuming both the sounds described by the OP and the source of the aforementioned ambience are correct.

Just to clarify what OP said, we're not wanting to remove the stock fan whirring sounds that come with the base game -- that's fine, we like them. What we actually want to remove (or at least mute) are the additional sounds of unknown origin that only surface when this mod is installed. If a complete removal isn't feasible, we'd at least like to be able to turn down the offending sounds independent of stock ambience, as (in my opinion at least) they are incredibly annoying and actually serve to stress me out more than a flight of the plane I was trying to build in the first place.

Thanks,


ActrixEV

**Comment by ensou04** [comment]
This mod does not add the sounds as described, those are stock sounds and has always been there. RSE isn't supposed to be running during VAB context, only during Flight. I'll have to take a look into this because the only way I could imagine happening is if somehow RSE is still running when you switch to VAB and somehow increases the volume.

One possible and simpler explanation is:
When you install RSE, all Flight sounds are actually quieter than usual with the Limiter Feature activated.
This is on by default to save your speakers and ears from digital clipping and makes flight sounds more pleasing and detailed.
Because of this, we'll have a tendency to bring up our speaker or headphone volume to compensate. 
But once we go back to the VAB, whatever quiet sounds was there before are now louder because of us turning our speaker volume up.

**Comment by ActrixEV** [comment]
I see. I'll fiddle around with some settings and report back if I find anything.

**Comment by JonnyOThan** [comment]
I think we finally got to the bottom of this: it happens when you don’t install the config files.
